## Importing Pandas, Numpy, Matplotlib, Seaborn and Warnings Library

In [1]:
# Basic Import
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
import warnings
warnings.filterwarnings('ignore')

### Import CSV Data as Pandas DataFrame

In [2]:
matches = pd.read_csv("data/matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0,0,2024,Liverpool
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0,1,2024,Liverpool
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0,0,2024,Liverpool
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0,0,2024,Liverpool
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0,0,2024,Liverpool

In [4]:
matches.shape

(1892, 27)

Calculate amount of matches expected to be played in 3 full seasons

In [5]:
# 3 seasons * 20 teams * 38 matches
3 * 20 * 38

2280

Check matches played by team

In [6]:
matches["team"].value_counts()

team
Liverpool                   95
Newcastle United            95
Everton                     95
Crystal Palace              95
Wolverhampton Wanderers     95
Chelsea                     95
Manchester United           95
Aston Villa                 95
West Ham United             94
Brighton and Hove Albion    94
Tottenham Hotspur           94
Arsenal                     94
Brentford                   94
Manchester City             94
Southampton                 76
Leeds United                76
Leicester City              76
Burnley                     57
Fulham                      57
Nottingham Forest           57
Bournemouth                 56
Watford                     38
Norwich City                38
Sheffield United            19
Luton Town                  18
Name: count, dtype: int64

Number of matches played by a particular team

In [7]:
matches[matches["team"] == "Manchester United"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2021-08-14,12:30,Premier League,Matchweek 1,Sat,Home,W,5.0,1.0,Leeds United,...,Match Report,NaN,16.0,8.0,18.2,0.0,0,0,2022,Manchester United
1,2021-08-22,14:00,Premier League,Matchweek 2,Sun,Away,D,1.0,1.0,Southampton,...,Match Report,NaN,15.0,3.0,15.1,1.0,0,0,2022,Manchester United
2,2021-08-29,16:30,Premier League,Matchweek 3,Sun,Away,W,1.0,0.0,Wolves,...,Match Report,NaN,10.0,3.0,18.8,1.0,0,0,2022,Manchester United
3,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,1.0,Newcastle Utd,...,Match Report,NaN,21.0,6.0,20.5,0.0,0,0,2022,Manchester United
5,2021-09-19,14:00,Premier League,Matchweek 5,Sun,Away,W,2.0,1.0,West Ham,...,Match Report,NaN,17.0,10.0,17.1,0.0,0,0,2022,Manchester United
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,2023-12-06,20:15,Premier League,Matchweek 15,Wed,Home,W,2.0,1.0,Chelsea,...,Match Report,NaN,27.0,8.0,15.4,1.0,0,1,2024,Manchester United
22,2023-12-09,15:00,Premier League,Matchweek 16,Sat,Home,L,0.0,3.0,Bournemouth,...,Match Report,NaN,20.0,3.0,15.4,0.0,0,0,2024,Manchester United
24,2023-12-17,16:30,Premier League,Matchweek 17,Sun,Away,D,0.0,0.0,Liverpool,...,Match Report,NaN,6.0,1.0,16.3,0.0,0,0,2024,Manchester United
25,2023-12-23,12:30,Premier League,Matchweek 18,Sat,Away,L,0.0,2.0,West Ham,...,Match Report,NaN,11.0,3.0,18.1,0.0,0,0,2024,Manchester United
26,2023-12-26,20:00,Premier League,Matchweek 19,Tue,Home,W,3.0,2.0,Aston Villa,...,Match Report,NaN,13.0,7.0,18.0,1.0,0,0,2024,Manchester United

Show number of matches played by round

In [8]:
matches["round"].value_counts()

round
Matchweek 1     60
Matchweek 10    60
Matchweek 2     60
Matchweek 16    60
Matchweek 14    60
Matchweek 13    60
Matchweek 12    60
Matchweek 11    60
Matchweek 15    60
Matchweek 9     60
Matchweek 8     60
Matchweek 7     60
Matchweek 6     60
Matchweek 5     60
Matchweek 3     60
Matchweek 4     60
Matchweek 17    58
Matchweek 18    58
Matchweek 19    56
Matchweek 30    40
Matchweek 32    40
Matchweek 37    40
Matchweek 36    40
Matchweek 35    40
Matchweek 28    40
Matchweek 34    40
Matchweek 33    40
Matchweek 31    40
Matchweek 20    40
Matchweek 29    40
Matchweek 27    40
Matchweek 26    40
Matchweek 25    40
Matchweek 24    40
Matchweek 23    40
Matchweek 22    40
Matchweek 21    40
Matchweek 38    40
Name: count, dtype: int64

Explaining missing data:
<br>
- Dataset was scrapped during Matchweek 19 of the 2023/2024 season
- One match during Matchweek 17 was abandoned
- One match during Matchweek 18 was postponed

Cleanup

In [9]:
del matches["comp"]

In [10]:
del matches["notes"]

Change "data" dtype from object to datetime

In [11]:
matches["date"] = pd.to_datetime(matches["date"])

In [12]:
matches.dtypes

date            datetime64[ns]
time                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

Assign numerical values to venue (home vs away)

In [13]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

Assign numerical values to opponents

In [14]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

Assign numerical value to time

In [15]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

Assign numerical value to day

In [16]:
matches["day_code"] = matches["date"].dt.dayofweek

Assign numerical value to result
<br>
Win: 1
<br>
Loss: 0
<br>
Draw: 0 for both teams

In [17]:
matches["target"] = (matches["result"] == "W").astype("int")

In [18]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-13,16:30,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,1.3,...,0.0,0,0,2024,Liverpool,0,6,16,6,0
1,2023-08-19,15:00,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,3.0,...,1.0,0,1,2024,Liverpool,1,2,15,5,1
2,2023-08-27,16:30,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,0.9,...,1.0,0,0,2024,Liverpool,0,16,16,6,1
3,2023-09-03,14:00,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,2.5,...,0.0,0,0,2024,Liverpool,1,1,14,6,1
4,2023-09-16,12:30,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,2.5,...,0.0,0,0,2024,Liverpool,0,24,12,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Matchweek 35,Sat,Away,L,0.0,2.0,Aston Villa,0.5,...,0.0,0,0,2022,Norwich City,0,1,15,5,0
39,2022-05-08,14:00,Matchweek 36,Sun,Home,L,0.0,4.0,West Ham,0.8,...,1.0,0,0,2022,Norwich City,1,23,14,6,0
40,2022-05-11,19:45,Matchweek 21,Wed,Away,L,0.0,3.0,Leicester City,1.1,...,0.0,0,0,2022,Norwich City,0,11,19,2,0
41,2022-05-15,14:00,Matchweek 37,Sun,Away,D,1.0,1.0,Wolves,1.1,...,0.0,0,0,2022,Norwich City,0,24,14,6,0
42,2022-05-22,16:00,Matchweek 38,Sun,Home,L,0.0,5.0,Tottenham,0.5,...,0.0,0,0,2022,Norwich City,1,21,16,6,0

50 estimators

In [19]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

### Split DataFrame 2/3 for Training and 1/3 for Testing

In [20]:
train = matches[matches["date"] < '2023-02-25']
test = matches[matches["date"] > '2023-02-25']
train.shape, test.shape

((1224, 30), (656, 30))

Define predictors

In [21]:
predictors = ["venue_code", "opp_code", "hour", "day_code", "xg"]

In [22]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [23]:
preds = rf.predict(test[predictors])

In [24]:
acc = accuracy_score(test["target"], preds)

### Prediction accuracy

In [25]:
acc

0.6814024390243902

In [26]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [27]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          297   96
1          113  150

Revising Accuracy Metric to Focus on Win Prediction

In [28]:
precision_score(test["target"], preds)

0.6097560975609756

Wins were correctly predicted 60% of the time

## Improving Precision with Rolling Averages

### Split DataFrame by Team

In [29]:
grouped_matches = matches.groupby("team")

In [30]:
group = grouped_matches.get_group("Manchester United")

In [31]:
group

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-14,20:00,Matchweek 1,Mon,Home,W,1.0,0.0,Wolves,2.2,...,0.0,0,0,2024,Manchester United,1,24,20,0,1
1,2023-08-19,17:30,Matchweek 2,Sat,Away,L,0.0,2.0,Tottenham,2.1,...,1.0,0,0,2024,Manchester United,0,21,17,5,0
2,2023-08-26,15:00,Matchweek 3,Sat,Home,W,3.0,2.0,Nott'ham Forest,2.8,...,0.0,1,1,2024,Manchester United,1,18,15,5,1
3,2023-09-03,16:30,Matchweek 4,Sun,Away,L,1.0,3.0,Arsenal,0.9,...,0.0,0,0,2024,Manchester United,0,0,16,6,0
4,2023-09-16,15:00,Matchweek 5,Sat,Home,L,1.0,3.0,Brighton,1.0,...,1.0,0,0,2024,Manchester United,1,4,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,2022-04-23,12:30,Matchweek 34,Sat,Away,L,1.0,3.0,Arsenal,1.8,...,0.0,0,1,2022,Manchester United,0,0,12,5,0
45,2022-04-28,19:45,Matchweek 37,Thu,Home,D,1.0,1.0,Chelsea,0.5,...,0.0,0,0,2022,Manchester United,1,6,19,3,0
46,2022-05-02,20:00,Matchweek 35,Mon,Home,W,3.0,0.0,Brentford,2.0,...,1.0,1,1,2022,Manchester United,1,3,20,0,1
47,2022-05-07,17:30,Matchweek 36,Sat,Away,L,0.0,4.0,Brighton,0.9,...,1.0,0,0,2022,Manchester United,0,4,17,5,0
48,2022-05-22,16:00,Matchweek 38,Sun,Away,L,0.0,1.0,Crystal Palace,0.7,...,1.0,0,0,2022,Manchester United,0,7,16,6,0

Compute rolling averages

In [32]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [33]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt", "xg"]
new_cols = [f"{c}_rolling" for c in cols]

In [34]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling',
 'xg_rolling']

In [35]:
rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling,xg_rolling
3,2021-09-11,15:00,Matchweek 4,Sat,Home,W,4.0,1.0,Newcastle Utd,2.5,...,1,2.333333,0.666667,13.666667,4.666667,17.366667,0.666667,0.000000,0.000000,1.300000
5,2021-09-19,14:00,Matchweek 5,Sun,Away,W,2.0,1.0,West Ham,2.0,...,1,2.000000,0.666667,15.333333,4.000000,18.133333,0.666667,0.000000,0.000000,1.633333
7,2021-09-25,12:30,Matchweek 6,Sat,Home,L,0.0,1.0,Aston Villa,2.2,...,0,2.333333,0.666667,16.000000,6.333333,18.800000,0.333333,0.000000,0.000000,1.700000
9,2021-10-02,12:30,Matchweek 7,Sat,Home,D,1.0,1.0,Everton,1.0,...,0,2.000000,1.000000,21.666667,6.666667,19.100000,0.666667,0.000000,0.333333,2.233333
10,2021-10-16,15:00,Matchweek 8,Sat,Away,L,2.0,4.0,Leicester City,1.2,...,0,1.000000,1.000000,19.000000,6.666667,17.300000,0.666667,0.000000,0.333333,1.733333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,2023-12-06,20:15,Matchweek 15,Wed,Home,W,2.0,1.0,Chelsea,4.1,...,1,1.333333,0.333333,10.333333,2.666667,16.533333,0.333333,0.333333,0.333333,1.633333
22,2023-12-09,15:00,Matchweek 16,Sat,Home,L,0.0,3.0,Bournemouth,1.1,...,0,1.666667,0.666667,14.333333,4.000000,17.000000,0.333333,0.333333,0.666667,2.266667
24,2023-12-17,16:30,Matchweek 17,Sun,Away,D,0.0,0.0,Liverpool,0.8,...,0,0.666667,1.666667,18.333333,4.000000,16.333333,0.333333,0.000000,0.333333,1.900000
25,2023-12-23,12:30,Matchweek 18,Sat,Away,L,0.0,2.0,West Ham,1.0,...,0,0.666667,1.333333,17.666667,4.000000,15.700000,0.333333,0.000000,0.333333,2.000000
26,2023-12-26,20:00,Matchweek 19,Tue,Home,W,3.0,2.0,Aston Villa,1.1,...,1,0.000000,1.666667,12.333333,2.333333,16.600000,0.000000,0.000000,0.000000,0.966667

In [36]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [37]:
matches_rolling = matches_rolling.droplevel('team')

In [38]:
matches_rolling.index = range(matches_rolling.shape[0])

In [39]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling,xg_rolling
0,2021-09-11,15:00,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,2.7,...,1,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000,0.600000
1,2021-09-18,15:00,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,1.1,...,1,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000,1.066667
2,2021-09-26,16:30,Matchweek 6,Sun,Home,W,3.0,1.0,Tottenham,1.1,...,1,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000,1.333333
3,2021-10-02,17:30,Matchweek 7,Sat,Away,D,0.0,0.0,Brighton,0.4,...,0,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000,1.633333
4,2021-10-18,20:00,Matchweek 8,Mon,Home,D,2.0,2.0,Crystal Palace,1.7,...,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000,0.866667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1812,2023-12-05,19:30,Matchweek 15,Tue,Home,W,1.0,0.0,Burnley,0.8,...,1,1.666667,2.000000,10.666667,4.000000,15.300000,0.000000,0.333333,0.333333,1.400000
1813,2023-12-09,15:00,Matchweek 16,Sat,Home,D,1.0,1.0,Nott'ham Forest,1.2,...,0,1.333333,1.666667,7.333333,4.000000,14.400000,0.333333,0.333333,0.333333,0.966667
1814,2023-12-17,14:00,Matchweek 17,Sun,Away,L,0.0,3.0,West Ham,0.7,...,0,1.000000,1.000000,7.666667,3.666667,13.933333,0.333333,0.000000,0.000000,0.900000
1815,2023-12-24,13:00,Matchweek 18,Sun,Home,W,2.0,1.0,Chelsea,1.3,...,1,0.666667,1.333333,10.333333,3.666667,17.166667,0.333333,0.000000,0.000000,0.900000
1816,2023-12-27,19:30,Matchweek 19,Wed,Away,W,4.0,1.0,Brentford,2.1,...,1,1.000000,1.666667,12.666667,4.333333,17.466667,0.333333,0.000000,0.000000,1.066667

## Retraining Model

In [40]:
from sklearn.model_selection import train_test_split
def make_predictions(data, predictors):
    train = data[data["date"] < '2023-02-25']
    test = data[data["date"] > '2023-02-25']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [41]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [42]:
precision

0.6434426229508197

In [43]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [44]:
combined

,actual,predicted,date,team,opponent,result
59,1,1,2023-03-01,Arsenal,Everton,W
60,1,1,2023-03-04,Arsenal,Bournemouth,W
61,1,1,2023-03-12,Arsenal,Fulham,W
62,1,1,2023-03-19,Arsenal,Crystal Palace,W
63,1,1,2023-04-01,Arsenal,Leeds United,W
...,...,...,...,...,...,...
1812,1,0,2023-12-05,Wolverhampton Wanderers,Burnley,W
1813,0,0,2023-12-09,Wolverhampton Wanderers,Nott'ham Forest,D
1814,0,0,2023-12-17,Wolverhampton Wanderers,West Ham,L
1815,1,0,2023-12-24,Wolverhampton Wanderers,Chelsea,W
1816,1,1,2023-12-27,Wolverhampton Wanderers,Brentford,W

In [45]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {
    "Brighton and Hove Albion": "Brighton",
    "Manchester United": "Manchester Utd",
    "Newcastle United": "Newcastle Utd",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves",
    "Nottingham Forest": "Nott'ham Forest",
    "Sheffield United": "Sheffield Utd"
}
mapping = MissingDict(**map_values)

In [46]:
mapping["Nottingham Forest"]

"Nott'ham Forest"

In [47]:
combined["new_team"] = combined["team"].map(mapping)

In [48]:
combined

,actual,predicted,date,team,opponent,result,new_team
59,1,1,2023-03-01,Arsenal,Everton,W,Arsenal
60,1,1,2023-03-04,Arsenal,Bournemouth,W,Arsenal
61,1,1,2023-03-12,Arsenal,Fulham,W,Arsenal
62,1,1,2023-03-19,Arsenal,Crystal Palace,W,Arsenal
63,1,1,2023-04-01,Arsenal,Leeds United,W,Arsenal
...,...,...,...,...,...,...,...
1812,1,0,2023-12-05,Wolverhampton Wanderers,Burnley,W,Wolves
1813,0,0,2023-12-09,Wolverhampton Wanderers,Nott'ham Forest,D,Wolves
1814,0,0,2023-12-17,Wolverhampton Wanderers,West Ham,L,Wolves
1815,1,0,2023-12-24,Wolverhampton Wanderers,Chelsea,W,Wolves
1816,1,1,2023-12-27,Wolverhampton Wanderers,Brentford,W,Wolves

In [49]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [50]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,1,1,2023-03-01,Arsenal,Everton,W,Arsenal,0,0,Everton,Arsenal,L,Everton
1,1,1,2023-03-04,Arsenal,Bournemouth,W,Arsenal,0,0,Bournemouth,Arsenal,L,Bournemouth
2,1,1,2023-03-12,Arsenal,Fulham,W,Arsenal,0,0,Fulham,Arsenal,L,Fulham
3,1,1,2023-03-19,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
4,1,1,2023-04-01,Arsenal,Leeds United,W,Arsenal,0,0,Leeds United,Arsenal,L,Leeds United
...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,1,0,2023-12-05,Wolverhampton Wanderers,Burnley,W,Wolves,0,0,Burnley,Wolves,L,Burnley
640,0,0,2023-12-09,Wolverhampton Wanderers,Nott'ham Forest,D,Wolves,0,0,Nottingham Forest,Wolves,D,Nott'ham Forest
641,0,0,2023-12-17,Wolverhampton Wanderers,West Ham,L,Wolves,1,0,West Ham United,Wolves,W,West Ham
642,1,0,2023-12-24,Wolverhampton Wanderers,Chelsea,W,Wolves,0,1,Chelsea,Wolves,L,Chelsea
643,1,1,2023-12-27,Wolverhampton Wanderers,Brentford,W,Wolves,0,0,Brentford,Wolves,L,Brentford

In [51]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()

actual_x
1    131
0     43
Name: count, dtype: int64

In [52]:
correct = merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()[1]
incorrect = merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()[0]

In [53]:
correct / (correct + incorrect)

0.7528735632183908